services:
  router:
    image: ghcr.io/apollographql/router:v1.0.0
    volumes:
      - ./router.yaml:/dist/config/router.yaml
      - ./supergraph.graphql:/dist/config/supergraph.graphql
    ports:
      - 4000:4000
    command: -c config/router.yaml -s config/supergraph.graphql
  inventory:
    image: apollo-federation-implementations/inventory
    ports:
      - 4003:4003
  users:
    image: apollo-federation-implementations/users
    ports:
      - 4002:4002
