[package]
name = "federation-async-graphql-compatibility"
version = "0.3.0"
edition = "2021"

[dependencies]
actix-web = "4"
async-graphql = { version = "4", features = ["apollo_tracing"] }
async-graphql-actix-web = "4"
