name: Subgraph Test

on:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
      format:
        default: markdown
        type: string
    secrets:
      TEST_URL:
        required: false
      API_KEY:
        required: false

jobs:
  compatibility:
    name: compatibility-${{ inputs.library }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies and build
        run: npm install
      - name: Compatibility test
        run: npm run compatibility:test -- docker --debug --compose implementations/${{ inputs.library }}/docker-compose.yaml --schema implementations/_template_library_/products.graphql --format ${{ inputs.format }}
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TEST_URL: ${{ secrets.TEST_URL }}
      - name: Generate Results Summary
        run: |
          if [[ ${{ inputs.format }} == "json" ]]; then
            jq -s '.[0] + {tests: .[1]}' implementations/${{ inputs.library }}/metadata.json results.json > results-${{ inputs.library }}.json
            echo "RESULTS_FILE=results_${{ inputs.library }}.json" >> $GITHUB_ENV
          else
            cat results.md >> $GITHUB_STEP_SUMMARY
            mv results.md results-${{ inputs.library }}.md
            echo "RESULTS_FILE=results-${{ inputs.library }}.md" >> $GITHUB_ENV
          fi
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RESULTS_FILE }}
          path: ./${{ env.RESULTS_FILE }}
          retention-days: 1
